model: 'PlainRepConv'
comment: 'Val_X2_BEST'
## parameters for plain
scale: 2
colors: 3
m_plainsr: 4
c_plainsr: 32
with_bn: 0
act_type: 'relu'
pretrain:

## loss function & optimizer
loss: 'dwa'

## optimizer:
optimizer: adam
lr: 0.0005

## scheduler:
scheduler: 'CosineAnnealingWarmRestarts'
decays: [200, 400, 600]
gamma: 0.5
wd: 0.0
min_lr: 0.000001

## parameters for model training
epochs: 200

patch_size: 384
batch_size: 8
data_repeat: 20
data_augment: 1

log_every: 100
test_every: 1
log_path: "./experiments/Val_X2_Best"
log_name:
save_val_image: False

wandb: True

## Fp16 training
mixed_pred: True
normalize: True

## hardware specification
threads: 1

## data specification

data_path: "C:/Users/zh321/Github/simple_real_time_super_resolution/dataset/SR/RLSR/DIV2K_X2"
test_path: "C:/Users/zh321/Github/simple_real_time_super_resolution/dataset/SR/RLSR/val_phase_X2"
#data_path: '/dataset/SR/RLSR/DIV2K_X2/'
#test_path: '/dataset/SR/RLSR/val_phase_X2/'
eval_sets: ['DIV2K']